export const candidateData = {
  profile: {
    name: "Alex Chen",
    email: "alex.chen@example.com",
    avatar: "/developer-working.png",
    title: "Full Stack Developer",
    level: "Advanced",
    joinedDate: "2024-01-15",
    isPublic: true,
    targetRole: "Senior Software Engineer at Google",
  },
  stats: {
    totalPoints: 8450,
    promptIQScore: 87,
    assessmentsCompleted: 45,
    practiceHours: 127,
    currentStreak: 12,
    longestStreak: 28,
    rank: 156,
    totalUsers: 12450,
  },
  recentActivity: [
    {
      id: "1",
      type: "assessment",
      title: "React Advanced Patterns",
      points: 250,
      promptIQ: 92,
      timestamp: "2 hours ago",
      status: "completed",
    },
    {
      id: "2",
      type: "practice",
      title: "TypeScript Generics Deep Dive",
      points: 180,
      promptIQ: 85,
      timestamp: "1 day ago",
      status: "completed",
    },
    {
      id: "3",
      type: "achievement",
      title: "Unlocked: Prompt Master Badge",
      points: 500,
      timestamp: "2 days ago",
      status: "unlocked",
    },
    {
      id: "4",
      type: "assessment",
      title: "Node.js Microservices Architecture",
      points: 320,
      promptIQ: 88,
      timestamp: "3 days ago",
      status: "completed",
    },
  ],
  skills: [
    { name: "React", level: 92, assessments: 12 },
    { name: "TypeScript", level: 88, assessments: 15 },
    { name: "Node.js", level: 85, assessments: 10 },
    { name: "Python", level: 78, assessments: 8 },
    { name: "System Design", level: 72, assessments: 6 },
  ],
  achievements: [
    {
      id: "1",
      title: "Prompt Master",
      description: "Achieved PromptIQ score of 90+ in 10 assessments",
      icon: "🏆",
      unlockedDate: "2024-02-15",
    },
    {
      id: "2",
      title: "Code Evolution Expert",
      description: "Demonstrated excellent code iteration patterns",
      icon: "⚡",
      unlockedDate: "2024-02-10",
    },
    {
      id: "3",
      title: "Consistency Champion",
      description: "Maintained a 14-day practice streak",
      icon: "🔥",
      unlockedDate: "2024-02-05",
    },
  ],
  promptIQTrend: [
    { month: "Sep", score: 72 },
    { month: "Oct", score: 78 },
    { month: "Nov", score: 82 },
    { month: "Dec", score: 85 },
    { month: "Jan", score: 87 },
  ],
}
