export const practiceAssessments = [
  {
    id: "1",
    title: "React Hooks Mastery",
    description: "Master useState, useEffect, useContext, and custom hooks with real-world scenarios",
    difficulty: "Intermediate",
    category: "Frontend",
    tags: ["React", "JavaScript", "Hooks"],
    duration: 60,
    questions: 12,
    points: 250,
    createdBy: "PromoraAI",
    creatorType: "official",
    completions: 1245,
    avgPromptIQ: 84,
    isPublic: true,
  },
  {
    id: "2",
    title: "TypeScript Generics Deep Dive",
    description: "Learn advanced TypeScript generics, constraints, and utility types",
    difficulty: "Advanced",
    category: "Programming",
    tags: ["TypeScript", "Advanced", "Types"],
    duration: 90,
    questions: 15,
    points: 400,
    createdBy: "Sarah Johnson",
    creatorType: "candidate",
    completions: 856,
    avgPromptIQ: 88,
    isPublic: true,
  },
  {
    id: "3",
    title: "System Design Fundamentals",
    description: "Design scalable systems with load balancing, caching, and database optimization",
    difficulty: "Advanced",
    category: "System Design",
    tags: ["Architecture", "Scalability", "Databases"],
    duration: 120,
    questions: 8,
    points: 500,
    createdBy: "PromoraAI",
    creatorType: "official",
    completions: 2341,
    avgPromptIQ: 82,
    isPublic: true,
  },
  {
    id: "4",
    title: "Node.js API Development",
    description: "Build RESTful APIs with Express, authentication, and database integration",
    difficulty: "Intermediate",
    category: "Backend",
    tags: ["Node.js", "Express", "API"],
    duration: 75,
    questions: 10,
    points: 300,
    createdBy: "TechCorp Recruiters",
    creatorType: "recruiter",
    completions: 1567,
    avgPromptIQ: 85,
    isPublic: true,
  },
  {
    id: "5",
    title: "Python Data Structures",
    description: "Master lists, dictionaries, sets, and advanced data manipulation techniques",
    difficulty: "Beginner",
    category: "Programming",
    tags: ["Python", "Data Structures", "Basics"],
    duration: 45,
    questions: 15,
    points: 200,
    createdBy: "PromoraAI",
    creatorType: "official",
    completions: 3421,
    avgPromptIQ: 78,
    isPublic: true,
  },
  {
    id: "6",
    title: "AWS Cloud Architecture",
    description: "Design and deploy scalable applications on AWS with EC2, S3, and Lambda",
    difficulty: "Advanced",
    category: "DevOps",
    tags: ["AWS", "Cloud", "Infrastructure"],
    duration: 90,
    questions: 12,
    points: 450,
    createdBy: "Michael Chen",
    creatorType: "candidate",
    completions: 987,
    avgPromptIQ: 86,
    isPublic: true,
  },
]

export const categories = [
  { name: "All", count: practiceAssessments.length },
  { name: "Frontend", count: 1 },
  { name: "Backend", count: 1 },
  { name: "System Design", count: 1 },
  { name: "Programming", count: 2 },
  { name: "DevOps", count: 1 },
]

export const difficulties = ["All", "Beginner", "Intermediate", "Advanced"]

export const creatorTypes = [
  { label: "All", value: "all" },
  { label: "PromoraAI Official", value: "official" },
  { label: "Recruiters", value: "recruiter" },
  { label: "Community", value: "candidate" },
]
