export const publicCandidates = [
  {
    id: "1",
    name: "Alex Chen",
    email: "alex.chen@example.com",
    title: "Full Stack Developer",
    avatar: "/placeholder.svg?key=lps8g",
    location: "San Francisco, CA",
    promptIQScore: 87,
    totalPoints: 8450,
    level: "Advanced",
    skills: ["React", "TypeScript", "Node.js", "System Design"],
    assessmentsCompleted: 45,
    targetRole: "Senior Software Engineer at Google",
    bio: "Passionate about building scalable web applications with modern technologies. Strong AI collaboration skills with focus on prompt engineering.",
    isPublic: true,
    joinedDate: "2024-01-15",
    achievements: ["Prompt Master", "Code Evolution Expert"],
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    title: "Frontend Engineer",
    avatar: "/placeholder.svg?key=abc123",
    location: "New York, NY",
    promptIQScore: 92,
    totalPoints: 12340,
    level: "Expert",
    skills: ["React", "Vue.js", "CSS", "UI/UX"],
    assessmentsCompleted: 67,
    targetRole: "Lead Frontend Engineer at Meta",
    bio: "Crafting beautiful user experiences with a data-driven approach. Expert in modern frontend frameworks and AI-assisted development.",
    isPublic: true,
    joinedDate: "2023-11-20",
    achievements: ["Prompt Master", "Consistency Champion", "UI Wizard"],
  },
  {
    id: "3",
    name: "Michael Rodriguez",
    email: "michael.rodriguez@example.com",
    title: "Backend Developer",
    avatar: "/placeholder.svg?key=xyz789",
    location: "Austin, TX",
    promptIQScore: 85,
    totalPoints: 9870,
    level: "Advanced",
    skills: ["Python", "Django", "PostgreSQL", "AWS"],
    assessmentsCompleted: 52,
    targetRole: "Senior Backend Engineer at Netflix",
    bio: "Building robust APIs and scalable backend systems. Strong focus on system architecture and database optimization.",
    isPublic: true,
    joinedDate: "2024-02-10",
    achievements: ["Code Evolution Expert", "Database Master"],
  },
  {
    id: "4",
    name: "Emily Watson",
    email: "emily.watson@example.com",
    title: "DevOps Engineer",
    avatar: "/placeholder.svg?key=dev456",
    location: "Seattle, WA",
    promptIQScore: 89,
    totalPoints: 10560,
    level: "Advanced",
    skills: ["Kubernetes", "Docker", "AWS", "CI/CD"],
    assessmentsCompleted: 58,
    targetRole: "Senior DevOps Engineer at Amazon",
    bio: "Automating infrastructure and improving deployment pipelines. Passionate about cloud architecture and container orchestration.",
    isPublic: true,
    joinedDate: "2023-12-05",
    achievements: ["Automation Expert", "Cloud Architect"],
  },
]

export const profileData = {
  ...publicCandidates[0],
  promptIQTrend: [
    { month: "Sep", score: 72 },
    { month: "Oct", score: 78 },
    { month: "Nov", score: 82 },
    { month: "Dec", score: 85 },
    { month: "Jan", score: 87 },
  ],
  recentAssessments: [
    {
      title: "React Advanced Patterns",
      promptIQ: 92,
      points: 250,
      date: "2025-01-15",
      rank: "Top 5%",
    },
    {
      title: "System Design Fundamentals",
      promptIQ: 85,
      points: 500,
      date: "2025-01-10",
      rank: "Top 10%",
    },
    {
      title: "TypeScript Generics",
      promptIQ: 88,
      points: 400,
      date: "2025-01-05",
      rank: "Top 8%",
    },
  ],
  skillEvolution: [
    { skill: "React", history: [65, 72, 78, 85, 92] },
    { skill: "TypeScript", history: [58, 68, 75, 82, 88] },
    { skill: "System Design", history: [45, 55, 65, 70, 72] },
  ],
}
